chore: Update version-bump.yml to use "Release" instead of "Bump version"

diff --git a/.github/workflows/version-bump.yml b/.github/workflows/version-bump.yml
--- a/.github/workflows/version-bump.yml
+++ b/.github/workflows/version-bump.yml
@@ -1,12 +1,12 @@
-name: Bump version
+name: Release
 
 on:
   push:
     branches:
-      - main
+      - main  # Change this to your main branch name
 
 jobs:
-  bump-version:
+  release:
     runs-on: ubuntu-latest
 
     steps:
@@ -16,27 +16,28 @@ jobs:
       - name: Set up Python
         uses: actions/setup-python@v2
         with:
-          python-version: 3.12
-
-      - name: Install dependencies
-        run: |
-          python -m pip install --upgrade pip
-          pip install bump2version
+          python-version: '3.12'  # Specify your desired Python version
 
       - name: Install Poetry
-        uses: snok/install-poetry@v1
+        run: pip install poetry
 
-      - name: Extract version number
+      - name: Install dependencies
+        run: poetry install
+
+      - name: Extract version from pyproject.toml
         id: extract_version
         run: |
-          version=$(poetry version -s)
-          echo "VERSION=$version" >> $GITHUB_ENV
+          VERSION=$(poetry version -s)
+          echo "VERSION=$VERSION" >> $GITHUB_ENV
 
-      - name: Create and push tag
+      - name: Create GitHub Release
         env:
           GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
+          VERSION: ${{ env.VERSION }}
         run: |
-          git config --global user.name "github-actions[bot]"
-          git config --global user.email "github-actions[bot]@users.noreply.github.com"
-          git tag "v${{ env.VERSION }}"
-          git push origin "v${{ env.VERSION }}"
+          if [ ! -z "$VERSION" ]; then
+            gh release create $VERSION --notes "Release $VERSION"
+          else
+            echo "Version could not be determined."
+            exit 1
+          fi
